### ISSUE TITLE
Doesn't load in Firefox when using a modal dialog box

### ISSUE THREAD

**Issue by jeppeliisberg** [nathancolgate/s3-swf-upload-plugin#14]
Hi, when using this plugin, FireFox does not insert the flash into my html. I do not get eny errors or warnings from the error console, but all that is left in my HTML is a hidden div like this:

```
<div id="s3_swf_1">
  Please <a href="http://www.adobe.com/go/getflashplayer">Update</a> your Flash Player to Flash v9.0.0 or higher...
</div>
```

Any idea why this is? What can I do to provide better debugging information and/or resolve this?
- Jeppe

**Comment by nathancolgate** [comment]
But it does load in other browsers? Which ones?

**Comment by jeppeliisberg** [comment]
It work fine with Chrome and Safari. Haven't tested in other browsers (IE to come).

**Comment by jeppeliisberg** [comment]
I've been looking more into the issue, and have encountered more problems (will create seperate ticket) and only partly understood the problem.

First off - Testing with IE proved to have the same issue as FF, and then some...

Second - We're using jquery, rendering the uploader in jQuerys 'dialog' modal box, which seems to be troublesome. I can make the uploader work when I don't put it into a modal and load it using ajax. I still have no idea why this is, but I've managed to do a workaround (preloading uploader html thus avoiding ajax) that solves the issue for now.

It's hard for me to have any idea of the origin of this issue, since the interaction between jQuery dialog, ajax and the s3_swf_uploader javascript is more or less a jungle for me.

If you would like to look into this issue, I can try to reproduce it in a vanilla rails project, would that be of any use to you?

**Comment by nathancolgate** [comment]
I can imagine that running this is a modal dialog box opens the problem up to a multitude of possibilities.  But there is always a good chance that someone else is working through the same problem, so your vanilla app might be helpful!

**Comment by jeppeliisberg** [comment]
http://github.com/jeppeliisberg/uploadtest

Hope you get a chance to take a look at it - please let me know if you can't reproduce the error.

**Comment by mdi** [comment]
I'm running into this same exact problem. Did you ever figure it out?

**Comment by mdi** [comment]
Nevermind. I solved it by upgrading the embedded SWFObject v2.1 to v2.2.

**Comment by andrewhavens** [comment]
I am also having the same issue in Firefox and have seen this happen on Windows and Mac, even in newer versions of Firefox (v12). I have a wizard style form that is completed one step at a time. Most of the form is hidden on page load, but as the user completes more of the form and clicks the continue button, the next section of the form "slides down" and the previous step "slides up". One of the reasons I do this is to gather information before specifying the filename that will be used when uploading to Amazon. So, I don't "initialize" the s3-swf-upload until the last step of the form. It appears as if the SWF is initialized, but the button image is never displayed, and nothing happens when you click on it. No problems in Safari, Chrome, or IE. I am already using SWFObject 2.2 so that is not the solution to this problem.

**Comment by nathancolgate** [comment]
If anyone has any advice on this issue, please feel free to add it here. But as of now, I don't think anyone is going to try and fix this as it appears to be a browser issue.
