### ISSUE TITLE
Multiple browse buttons not showing?

### ISSUE THREAD

**Issue by watson** [nathancolgate/s3-swf-upload-plugin#21]
When I try to put more than one browse-button on a single webpage, only the last one is shown. The &lt;object> tag is correctly inserted into the page, but Flash it self doesn't render it.

I'm on Chrome/Mac

**Comment by nathancolgate** [comment]
I'm not sure what might be causing that, but I probably won't be trying to sort this out (Multiple multiple file uploaders on one page! Craziness! :)).  If you want, throw your HTML in a gist somewhere and I'll take a look at it and see if there is anything glaring.

**Comment by watson** [comment]
Here is a gist: https://gist.github.com/711785

This is needed for pages where the user needs to upload different kind of files and where the type of file can't be detected using, mime-type etc.

This could for instance be a user-profile page where the user is promted to upload both a profile picture and some other pictures. In that case we need to have two different uploaders for handling the two different kind of uploads - otherwise we don't have any chance of guessing which is the profile-picture.

**Comment by mrrooijen** [comment]
I'm also actually in the need of this for my app. When I add the view helper multiple times it does increment the `@count` variable but since it loads in the javascript every time, it dies.

Before I switched to this gem, I was actually uploading from Client -> My App -> S3. I also used a Flash based uploader, but it didn't go directly to S3. The solution I had was to just use a simple javascript based uploader, since that also goes through my app. I like this approach better, where you just upload from Client -> S3 directly using your gem.

The reason I have multiple uploaders on a single page is because every file can have "revisions". So for each file there needs to be a new uploader. I'm considering doing this with Javascript and just go through my app, since it's just one file at a time anyway. However, do you by any chance know of a tool that can upload directly to S3 in pure Javascript? Because I think adding multiple Flash-based uploaders, at least with this gem at the moment is out of the question. Would probably introduce a lot of complexity and I don't think it's a common issue. :)

Thanks for the amazing gem though, it is extremely simple to use and highly customizable. I see myself using this in a lot of future projects!

**Comment by adamflorin** [comment]
+1

The issue is: while the Rails helper is good about incrementing the ids for each SWF, the ActionScript does not know what its own id is. In S3Uploader.as, I see the line `ExternalInterface.call('s3_swf.init');`. But `s3_swf` is just a temporary var in s3_upload.js, and will just point to whatever the most recent object is, so if you embed two SWF uploaders on a page, one of them will get init'd twice, and the other not at all.

I think the best solution would be to pass the SWF's `id` in as a flashvar when you embed it with swfobject. Then any `ExternalInterface` calls from the AS could use that. Right?

I thought maybe I could get fancy and tease these calls apart (by overriding `s3_swf.init()` in the JS), but on top of this there's a race condition between the two SWFs as to which will call `init` first. In short, the SWF just _has_ to know its own id.

This would be _very_ handy, as I too have a scenario in which I need to let the user upload two types of files on one page (one MP3 and a handful of AIFFs, for example).

UPDATE: For now, I was able to work around the issue by containing each uploader in its own iframe, with JS coordinating all the uploads from the mothership, i.e., parent frame.

**Comment by joel1di1** [comment]
+1

I'd like to use several uploaders because I want to separate uploads on screen for users :
- "click here to choose your documents (.doc)"
- "click here to choose your images (.png)"

**Comment by darcy** [comment]
I needed this too for various reasons.

Based on the pointers in the comment from @adamflorin, I took a stab at getting this working. I updated the view helper to use the count to set a flashvar for the callbacks and likewise updated flex to use that new var... so, it should 'just work'. 

So far, it has been working great for us.

https://github.com/darcy/s3-swf-upload-plugin/commit/2eab5a1e410b779c49c274a89db9bf0bf8f3a970

Thanks for the great plugin!

**Comment by willcosgrove** [comment]
That works great!  Thanks so much, you should submit a pull request.

**Comment by darcy** [comment]
Pull request sent.

**Comment by nathancolgate** [comment]
Thanks, @darcy!

**Comment by adamflorin** [comment]
Nice work, @darcy; glad to hear that solution turned out!!

**Comment by ziazek** [comment]
It's still not working for me. Only the last instance of the browse button is shown. The earlier-created instance doesn't render.
