### ISSUE TITLE
How does this handle security?

### ISSUE THREAD

**Issue by philipkd** [nathancolgate/s3-swf-upload-plugin#30]
I got this plugin working, it looks powerful and amazing. However, I'm trying to understand how secure it is. Why couldn't someone get to my /s3_uploads.xml, get a signature, and use it to upload files directly to S3, possibly overwriting other users' files?

Is there something I'm not understanding about how those signatures work? (i.e. that it only generates a valid signature if the request is coming from a swf file on the originating domain name).

**Comment by nathancolgate** [comment]
Hey Philip,

because the s3_uploads.xml signature is dynamically generated, you could use any variety of authentication to make sure that (for instance) there is a user logged in, or in a simpler scenario you could set a very short expiration date on the signature.

Currently I have it setup to skip the verification of the authenticity token (to help avoid issues with incoming flash requests) but I'm pretty sure there is a rack-based work around for that, too.

-N
