### ISSUE TITLE
How to display Amazon Response XML?

### ISSUE THREAD

**Issue by andrewhavens** [nathancolgate/s3-swf-upload-plugin#48]
I'm running into an error while trying to use this library that I am having trouble debugging. The `onUploadIOError` javascript callback method is being called, but the only thing that the `io_error_event` variable has is

```
text: "Amazon S3 returned an error: HTTP status 403."
```

I would like to debug further and inspect the XML response return from Amazon. I don't see a way to do that currently. Is there a way that we can pass a `debug: true` option to enable extra logging?

**Comment by nathancolgate** [comment]
"I don't see a way to do that currently. Is there a way that we can pass a debug: true option to enable extra logging?" Great idea, Andrew.

At one point I had all kinds of debugging coming out of the application, but I turned it off because... because I'm not that bright sometimes.

I know this is possible. Just a matter of someone sitting down and cranking it out.

**Comment by monicao** [comment]
In the mean time you can use Wireshark, or some other packet sniffer to get the responses from S3.

Here's a quick writeup of how to do it: http://blog.mochromatic.com/2012/01/19/debugging-http-errors-that-do-not-appear-in-firebug/

**Comment by nathancolgate** [comment]
Thanks, @monicao!
