### ISSUE TITLE
According to bundle aws-s3 is still a dependency 

### ISSUE THREAD

**Issue by shanlalit** [nathancolgate/s3-swf-upload-plugin#56]
Thanks for all the updates on this plug-in.

I was really happy to know that the aws dependency is over for this plug-in. According to this presentation on Rails performance (http://www.slideshare.net/slideshow/embed_code/8476299?startSlide=47) it adds 30K object to my application.

But gemspec still says - s.add_dependency('aws-s3', '~> 0.6.2')

That's why it's still installs aws-s3 and show it in Gemfile.lock as dependency.

**Comment by yuki24** [comment]
I added that dependency on #49 because README showed both _you’ll also need aws-s3_ and _there would be no dependency of aws/s3_. also there was no tests to ensure that everything works fine without `aws/s3`.
actually I have written Rspec examples for the ruby part in my fork and figured out `aws/s3` is unnecessary. hopefully I can send a pull request for this issue soon.

**Comment by shanlalit** [comment]
Thanks yuki,

I tested on my staging server (from my fork) and it seems to be working fine without aws/s3. If you say I can send this small change pull request right now.

**Comment by yuki24** [comment]
Thanks @shanlalit!

Please send it if you can. And we should also remove _you’ll also need aws-s3_ in README as well.

**Comment by shanlalit** [comment]
Sent a pull request, apologies for taking too long to send it.
